### ISSUE TITLE
Feature 1: User can browse through items

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/new-horizon-hub#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse through the items from the API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on buttons to show items from that category and browse through it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 1 08 15 PM](https://user-images.githubusercontent.com/88172055/134240329-68a0375b-5e13-4b9b-94c6-a66ab4a6d0a7.png)
![Screen Shot 2021-09-21 at 1 08 45 PM](https://user-images.githubusercontent.com/88172055/134240370-bed35bb4-c8d8-43c2-b781-9875d0d207d0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton and link JS/CSS files
- [x] Create top bar and create CSS
- [x] Set logo as the home button to get back to the home page
- [x] Create buttons and create CSS
- [x] Create different views for each of the categories
- [x] Add event listeners for switch views
- [x] Write JS code to request information from the API
- [x] Access DOM to create elements to display the items information
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
