### ISSUE TITLE
Feature 2: User can search items

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/new-horizon-hub#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search items.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can enter search queries into the search bar and related items will show up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 1 15 52 PM](https://user-images.githubusercontent.com/88172055/134241476-01deee78-6155-4ada-a6f8-ec02edabfdd5.png)
![Screen Shot 2021-09-21 at 1 16 00 PM](https://user-images.githubusercontent.com/88172055/134241488-f5b8fa21-9216-484d-a162-bec969682e9a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create search bar using input
- [x] Add eventlistener for text input in search bar on submit
- [x] Change the heading for the display screen to show "Results for...." 
- [x] Create function to go through API data and return the searched for items in the item boxes
- [x] Clear previous data on new search
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
