### ISSUE TITLE
Feature 3: User can view individual items

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/new-horizon-hub#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view individual items

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When selecting an item, a new screen comes up with more information about the item.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 1 20 51 PM](https://user-images.githubusercontent.com/88172055/134241863-141983f2-fa02-4a5d-a94a-dfb726fed50c.png)
![Screen Shot 2021-09-21 at 1 20 56 PM](https://user-images.githubusercontent.com/88172055/134241886-4f67149a-a536-4bbf-86cd-9e0c4e9e553d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add eventlisteners to each of the item squares
- [x] Listen for clicks on the items and call a function to clear the current boxes and replace it with a DOM generated info section
- [x] Have the info section provide catchphrase, rarity, months available, and time available
- [x] Clear the info section if a category button or home button is pressed.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
