### ISSUE TITLE
Feature 4: User can favorite an item

### ISSUE THREAD

**Issue by Jimmy-Vu** [Jimmy-Vu/new-horizon-hub#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite an item

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When pressing on the 'heart' icon that displays on the individual items, the said item will be added to a Favorites list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-21 at 1 23 29 PM](https://user-images.githubusercontent.com/88172055/134242179-cde1065c-02ca-4383-9848-831794e3eb9b.png)
![Screen Shot 2021-09-21 at 1 23 37 PM](https://user-images.githubusercontent.com/88172055/134242192-7fadd819-60d5-4c5e-bd73-7eed306cc1cb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add heart icon into DOM creation section for item card for when an item is favorited
- [ ] Create a class identifier for when the item is favorited
- [ ] Create an event listener for when the heart is clicked, the empty heart is then filled
- [ ] Add the favorite item into a specified array
- [ ] Create a favorite section in the UI
- [ ] Store favorite list into localStorage
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
